#!/usr/bin/env python3
"""Build writing/v2/Chapter_1_Introduction.docx from the revised Chapter 1 text."""
from docx import Document
from docx.shared import Pt

H1, H2, H3, P = "h1", "h2", "h3", "p"

content = [
(H1, "Chapter 1: Introduction"),

(P, "The ability to observe, interpret, and reconstruct human motion in three dimensions has become a foundational capability across a growing range of engineering and clinical disciplines. Robotic systems learn manipulation skills by watching people. Clinicians want objective records of how a patient moves. In both cases the demand is the same: accurate motion capture that does not require a laboratory to run. This thesis addresses one of the most technically demanding instances of this problem, the tracking and graphical reconstruction of bimanual object manipulation using a single consumer-grade RGB-D camera. The chapters that follow develop the theoretical foundations, system architecture, implementation, and evaluation of a complete end-to-end pipeline designed to meet this challenge."),

(H2, "1.1 Motivation"),

(P, "Human hands are the primary means through which people interact with the physical world. Coordinated two-handed tasks such as lifting, rotating, transferring, and assembling objects underlie activity in nearly every domain of daily life and professional practice. Capturing these interactions accurately in three dimensions opens up meaningful applications across several fields. In robotics, recorded human bimanual demonstrations serve as training data for imitation learning, allowing robotic arms to acquire dexterous manipulation skills without explicit programming [1], [2]. In virtual and augmented reality, skeletal and object pose data drive avatar animation and support simulation of physical tasks [3], [4]."),

(P, "In clinical medicine and rehabilitation the potential is particularly significant. Consider the assessment of an elderly patient with suspected motor impairment. A vision-based system that records and reconstructs the patient's full upper-body motion in three dimensions would allow a physician to review, at any convenient time, how the patient reaches for an object, transfers it between hands, or completes a routine daily living task. This kind of objective and repeatable motion record could assist physicians in diagnosing progressive conditions such as Parkinson's disease, stroke-related upper-limb deficits, or age-related decline in motor coordination [5], [6]. These conditions are currently evaluated through brief clinical observations, and brief observations may miss intermittent or subtle movement abnormalities."),

(P, "Reconstruction of this kind also protects patient privacy. If the physical movements can be replicated in the form of a digital twin, the physician does not need to review video of the patient at all. The recorded motion is played back on a graphical avatar, which can be made very accurate, while the patient's face, body, and home environment never leave the capture device."),

(P, "A practical sensing question follows from these requirements. A standard RGB camera on its own provides only two-dimensional information about the scene. Recovering metric 3D measurements requires either a depth-sensing camera or multiple synchronized viewpoints, such as the two-camera arrangement used in the FreeMoCap setup. A system that is low cost, requires no wearable hardware, and operates from a single fixed depth camera would make this kind of monitoring practical in outpatient clinics, assisted living facilities, and home settings alike."),

(P, "Existing approaches to capturing bimanual manipulation fall short of these practical requirements in different ways. Multi-camera motion capture systems deliver strong reconstruction accuracy, but they demand calibrated arrays of synchronized cameras, substantial physical infrastructure, and expert operation [7]. Routine clinical or field use is impractical under those conditions. Wearable sensor systems, including inertial measurement units and instrumented gloves, eliminate the need for camera arrays, but they must be attached and calibrated for each participant, they restrict the naturalness of movement, and they introduce hygiene concerns in patient-facing environments [8]. A single consumer-grade RGB-D camera avoids both drawbacks. It is inexpensive, places no hardware on the participant, and captures registered colour and metric depth data from one fixed viewpoint [9]."),

(P, "Using a single sensor to reconstruct bimanual upper-body motion with concurrent object tracking is genuinely difficult, however, and the difficulties go beyond simple measurement noise. When the two hands occlude each other or the object being manipulated, landmark detectors fail to produce reliable measurements at the very moments that matter most clinically [10], [11]. When landmarks overlap in the image plane or move toward the edges of the sensor's reliable depth range, direct depth readings become ambiguous or invalid [12]. Maintaining accurate spatial correspondence between all tracked body segments and objects requires careful coordinate frame calibration, and prior single-camera systems address this only partially [13]. Temporal filtering raises its own problem. The torso moves slowly and the fingers move fast, so smoothing every body segment with the same filter produces either over-smoothed distal joints or physically implausible intermediate poses [14]."),

(P, "These are not problems that additional sensor resolution alone can solve. What is needed is a structured mathematical framework that encodes the kinematic relationships between body segments, enforces physical constraints on joint motion, and provides a principled way to estimate joint configurations when measurements are missing or unreliable. The goal of this thesis is not to show that a kinematic model produces more accurate raw tracking than direct depth measurement under ideal, unoccluded conditions. Under such conditions, direct depth sampling is already effective. The goal is to establish a framework that remains physically consistent and recoverable under the realistic conditions of bimanual manipulation, where occlusion, dropout, and coordinate inconsistencies are the norm rather than the exception, and to lay the groundwork for future systems that can extend this approach with improved sensors and estimation methods."),

(P, "The Networked Robotics and Sensing Laboratory at Simon Fraser University has produced foundational work directly relevant to this objective. A hierarchical kinematic model of the human hand constructed from spatially tracked RGB-D landmarks was developed in [15]. That work demonstrated how palm and finger joint coordinate frames can be defined from MediaPipe measurements augmented with calibrated RealSense depth data, and how forward and inverse kinematic solutions can be derived within that structure. A subsequent study [16] extended this framework by formulating hand joint estimation as a Gaussian Bayesian Network problem, applying Maximum Likelihood Estimation over the hierarchical kinematic chain to recover anatomically consistent joint configurations when landmark measurements are occluded or corrupted by sensor noise. These two contributions establish the mathematical and algorithmic foundation on which the present thesis builds, extending the scope from single-hand reconstruction to the full bimanual upper-body setting with concurrent object tracking and Unity-based visualization. The following section reviews the broader landscape of related work, situates these prior contributions within it, and identifies the specific technical gaps that define the research objectives of this thesis."),

(H2, "1.2 Problem Statement and Literature Review"),

(P, "The technical challenges identified in Section 1.1 do not exist in isolation. Each reflects a broader research problem that has attracted significant attention across the computer vision, robotics, and human-computer interaction communities. This section reviews the relevant literature in three areas: hand and object tracking approaches, bimanual manipulation in motion analysis, and graphical reconstruction in robotics and virtual reality. The review identifies where current methods succeed, where they fall short, and what combination of gaps motivates the specific contributions of this thesis."),

(H3, "1.2.1 Hand and Object Tracking Approaches"),

(P, "Research on hand tracking from visual data spans several decades and has produced two broad families of methods. Appearance-based approaches learn a direct mapping from image features to hand pose. They are computationally efficient, but their robustness degrades when the hand is partially occluded or viewed from an unfamiliar angle. Model-based approaches instead fit a parameterized geometric or kinematic hand representation to sensor observations through optimization, providing stronger physical constraints at the cost of higher computational demand [17]. Both families have evolved substantially as sensing hardware improved. Understanding their trajectories helps place the present system within the field."),

(P, "Early wearable-based systems simplified the visual correspondence problem by encoding finger configuration directly in the sensor signal. Instrumented colour gloves are a representative example [18], and earlier work in our laboratory combined marker-based visual tracking of the hand with a vibrotactile glove to support haptic interaction with sensed objects [19]. The hardware these systems place on the user, however, makes them impractical for clinical and general-purpose applications. The arrival of consumer depth cameras, beginning with the Microsoft Kinect, shifted the field toward markerless approaches. Full-hand articulation tracking with a Kinect sensor was demonstrated in [20], where pose estimation was formulated as an optimization problem minimized using Particle Swarm Optimization over a geometric hand model. The work in [21] proposed a robust articulated Iterative Closest Point algorithm that integrates depth data and regularization priors into a unified solver, achieving reliable single-depth-camera hand tracking without restricting the range of motion. A complementary approach in [22] used a simplified sphere-based hand model optimized against sparse depth point clouds, with a part-detection stage handling initialization. These model-based methods established the feasibility of depth-based hand tracking. But they were designed primarily for single-hand scenarios, and they required explicit geometric models with per-user initialization."),

(P, "Deep learning subsequently transformed hand pose estimation by replacing hand-crafted geometric models with learned representations. The multi-view convolutional neural networks in [23] project depth images onto three orthogonal planes to regress 3D joint heatmaps, achieving robust pose estimation from a single depth image. More recently, transformer-based architectures have pushed accuracy further. The method in [24] recovers full 3D hand meshes from monocular RGB images by combining large Vision Transformer backbones with multi-dataset training, achieving state-of-the-art performance on in-the-wild benchmarks. A key limitation of transformer models was addressed in [25] by introducing a Graph-guided State Space block that captures joint spatial relationships more efficiently, reducing token count while maintaining competitive accuracy. These learning-based methods achieve impressive benchmark numbers. However, they rely on large annotated training datasets, they do not explicitly encode biomechanical constraints on joint motion, and they can behave unpredictably on sensor modalities or hand configurations underrepresented in their training data."),

(P, "MediaPipe, developed at Google, represents the current mainstream for lightweight landmark-based hand and body detection deployable without specialized hardware [26]. The MediaPipe Hands model uses a two-stage pipeline, first detecting the palm region and then regressing 21 keypoint positions within it. The output is a set of 2D pixel coordinates augmented with a relative depth estimate derived from image appearance rather than direct depth measurement. As noted in [3], this monocular depth estimate carries substantial uncertainty during fast motion, object contact, and occlusion of distal finger segments, which are precisely the conditions most common in manipulation tasks. Integrating MediaPipe with a calibrated RGB-D sensor resolves this ambiguity: the 2D pixel detections are back-projected through camera intrinsics using depth values sampled directly from the registered depth map, yielding metric 3D landmark coordinates from measurement rather than inference. This depth-fusion approach was formalized in [15] within a hierarchical hand kinematic framework, which defines palm and finger joint coordinate frames from the resulting 3D landmark point cloud and derives both forward and inverse kinematic solutions within that structure. The depth-augmentation strategy was independently validated in [12], which demonstrated that fusing stereo depth with MediaPipe landmark predictions substantially reduces joint localization error compared to monocular estimates alone, supporting the design decision adopted in this thesis."),

(P, "For object tracking, fiducial marker systems provide a reliable and computationally inexpensive path to pose estimation without requiring appearance models or training data. A systematic comparative evaluation in [27] tested ARTag, AprilTag, ArUco, and STag markers across detection rate, pose accuracy, and computational cost under varying noise and occlusion conditions, concluding that ArUco markers offer a favorable balance between robustness and efficiency for single-camera setups. The ArUco detection pipeline, implemented in OpenCV, uses adaptive thresholding and contour-based candidate extraction followed by Perspective-n-Point pose computation. Experimental analysis in [28] documented the relationship between marker size, viewing distance, and pose error for ArUco detections under controlled conditions, which informs the marker placement strategy adopted in this work. ArUco markers carry a further practical advantage in the context of this thesis. Each marker encodes a unique integer identifier alongside its geometric corners, so a single detection simultaneously resolves the identity of the tracked object and its pose relative to the camera, without a separate semantic classifier or object-specific appearance model. Although the detected pose contains both position and orientation, the present work focuses on the position trajectory of the manipulated object, for reasons discussed in Section 1.3."),

(P, "Occlusion between the hand and the tracked object is the most persistent failure mode for single-camera systems. One line of work [10] proposed decomposing two-interacting-hand pose estimation into separate per-hand problems by first de-occluding each hand using an inpainting-based Hand De-occlusion and Removal framework, enabling the use of single-hand estimators in interacting scenarios. A joint estimation approach was taken in [11], modeling hand-object interaction through a dense mutual attention mechanism that allows each modality to inform the other's pose prediction. These works demonstrate that occlusion cannot be treated as a simple data dropout problem. It requires either explicit recovery of the occluded region or a model that uses context from the visible parts to constrain the hidden ones. This observation directly motivates the interpolation-based occlusion recovery strategy developed in the present thesis, which reconstructs the trajectory of a lost landmark from its neighbouring measurements whenever its detection confidence falls below a defined threshold."),

(H3, "1.2.2 Bimanual Manipulation in Motion Analysis"),

(P, "Bimanual manipulation introduces challenges that go beyond what single-hand tracking research has addressed. When both hands are visible and unoccluded, the problem reduces to running two independent hand trackers in parallel. In practice the situation is harder. The two hands regularly overlap in the image plane, producing mutual occlusion. They interact with the same object, creating depth discontinuities at contact regions. And their motions are kinematically coupled through whatever they are holding, so errors in one hand's estimated pose can propagate inconsistencies into the reconstructed scene as a whole [17]. The temporal and spatial constraints of bimanual manipulation categories were formalized in [29], distinguishing symmetric tasks in which both hands perform mirror-image movements from asymmetric tasks in which they play complementary roles. This distinction matters for occlusion recovery design, since the two task types produce different patterns of landmark dropout."),

(P, "The construction of large-scale bimanual datasets has highlighted just how demanding the capture problem is. The InterHand2.6M dataset [30] was collected using between 80 and 140 synchronized high-resolution cameras, and OakInk2 [7] was built from a combination of multi-camera rigs and wearable sensors. The infrastructure required by these datasets underscores the gap between what is needed to produce ground-truth annotations and what is feasible in a clinical or field deployment. On the reconstruction side, RGB2Hands [31] was the first method to reconstruct two strongly interacting hands simultaneously from a single RGB video by modeling inter-hand contact constraints jointly. However, RGB2Hands does not extend to object tracking, and it relies on a learned neural model that requires substantial training data and is not straightforwardly interpretable in terms of physical joint constraints."),

(P, "In clinical applications, bimanual upper-limb assessment is central to monitoring stroke recovery and neurodegenerative disease progression. Objective kinematic measures of hand motion asymmetry have been shown to capture deficits that clinical observation scores may underrate [5]. A structured review of upper-limb function measurement in amyotrophic lateral sclerosis [6] concluded that existing clinical tools lack the sensitivity to track gradual functional change and that instrumented motion capture offers a more sensitive alternative. These findings reinforce the case for a low-overhead, marker-free reconstruction system. They also motivate the particular attention given in this thesis to physical plausibility in the reconstructed output, since clinically meaningful assessment depends on the system producing anatomically consistent motion even when sensor data is incomplete."),

(H3, "1.2.3 Graphical Reconstruction in Robotics and VR"),

(P, "Unity has become the dominant platform for avatar-driven motion replay across robotics and clinical applications. 3D human motion has been reconstructed in Unity from a monocular camera using kinematic retargeting [32], establishing that qualitative comparison between the reconstructed avatar and the original video sequence is a meaningful evaluation methodology when ground-truth joint angles are unavailable. A Kinect-based rehabilitation system built in Unity [33] showed that avatar-driven visual feedback supports clinical assessment of exercise quality. More recently, the RePose system [34] integrated MediaPipe landmark detection with a temporal smoothing network and streamed joint angles to a Unity patient avatar for rehabilitation monitoring, demonstrating end-to-end viability of the MediaPipe-to-Unity architecture adopted in the present thesis."),

(P, "A persistent engineering challenge in systems that stream RGB-D observations to Unity is the coordinate frame mismatch between the two environments. The Intel RealSense D435 uses a right-handed coordinate frame with the y-axis pointing downward, while Unity uses a left-handed frame with the y-axis pointing upward. This mismatch and its consequences for pose streaming were documented in [13] for single-hand grasping reconstruction, showing that without an explicit axis inversion and world-frame calibration step, streamed poses accumulate systematic spatial error. In the context of bimanual manipulation, this problem is more acute because the same transformation must be applied consistently across all tracked points per frame, including both skeletal landmarks and object poses, for the reconstructed scene to remain spatially coherent."),

(P, "It is worth being precise about where the real difficulty lies. Transferring landmark positions between environments is the easy part: a wrist position measured in sensor frame A can be moved into Unity world frame B with a single fixed change of coordinates. The avatar, however, is not driven by scattered points in space. It is driven kinematically, joint by joint, through rotations. The challenge is therefore to resolve the relative rotational angles of the actual body segments from the measured landmark coordinates, so that the same articulated motion can be reproduced on the avatar's kinematic chain. Resolving these angles robustly, frame after frame, is the central modeling problem of this thesis."),

(P, "The kinematic and estimation foundations most directly relevant to this problem come from two studies conducted within the same laboratory. The first study [15] presented a hierarchical 3D kinematic model of the human hand from calibrated RGB-D landmark data, using the palm as the root coordinate frame and deriving forward and inverse kinematic solutions for each finger, with qualitative Unity reconstruction demonstrating close agreement with observed hand postures across a range of grasping tasks. The second study [16] extended this framework by modeling each joint position as a Gaussian random variable within a Bayesian Network whose structure mirrors the kinematic chain, applying Maximum Likelihood Estimation to recover anatomically plausible configurations under occlusion and sensor noise, with the RealSense depth noise characterized as Gaussian consistent with the empirical findings reported in [35] and [36]. The present thesis builds directly on both contributions, scaling the approach from a single hand to the full bimanual upper-body setting with concurrent object tracking."),

(H3, "1.2.4 Gap Analysis and Motivation for This Work"),

(P, "The literature reviewed in the preceding sections reveals substantial progress in hand tracking, object pose estimation, bimanual motion analysis, and graphical reconstruction taken individually. What has not been demonstrated is a combination of all these capabilities within a single-sensor system that remains physically consistent under the realistic conditions of bimanual manipulation. Five specific gaps define the scope of this thesis. First, existing single-camera systems either fail silently when landmark confidence drops or apply uniform temporal smoothing that blurs all joints indiscriminately, without a recovery strategy that respects the different kinematics of the torso, upper arm, forearm, and hand [17]. Second, MediaPipe's monocular depth estimates carry significant uncertainty during manipulation tasks [3], and while depth fusion with a calibrated sensor resolves this, its integration with a full upper-body kinematic chain in a bimanual context has not been reported. Third, no published single-camera system reconstructs two hands and a manipulated object simultaneously within a single calibrated world frame. Existing bimanual methods omit object tracking [31], and existing hand-object methods address only the single-hand case [37]."),

(P, "The fourth gap concerns coordinate frame consistency across a complete bimanual pipeline. The RealSense-to-Unity transformation was documented in [13] for the single-hand case, but extending this calibration consistently to a full upper-body system with concurrent object tracking, where dozens of tracked points per frame must share the same world frame, has not been addressed in prior work. The fifth gap, and the one most central to the framing of this thesis, concerns the role of a principled mathematical framework in single-sensor reconstruction. The goal is not to demonstrate that a kinematic model outperforms direct depth tracking under ideal unoccluded conditions, where direct depth sampling is already effective. The goal is to establish a structured framework that remains physically consistent and recoverable under the conditions that actually arise during bimanual manipulation, where occlusion, dropout, and noisy depth readings occur together and cannot be resolved by sensor improvement alone."),

(P, "The kinematic and Bayesian estimation foundations developed in [15], [16] provide the mathematical basis for this framework at the level of a single hand. The present thesis extends and integrates these foundations into a system that addresses all five gaps together, combining RGB-D sensing, upper-body landmark extraction, ArUco-based object tracking, interpolation-based occlusion recovery, and Unity-based graphical reconstruction within a single coherent pipeline. This integration lays the groundwork for future work in which improved sensors, denser landmark sets, and more powerful estimation methods can be incorporated without requiring architectural redesign."),

(H2, "1.3 Research Objectives"),

(P, "The overarching goal of this thesis is to develop and evaluate a structured framework for tracking and reconstructing bimanual object manipulation from a single RGB-D sensor, with particular attention to physical consistency under the occlusion and measurement noise conditions that arise in practice."),

(P, "The first objective is to design and implement a calibrated RGB-D sensing pipeline using the Intel RealSense D435 that aligns depth and colour streams, establishes the camera intrinsic parameters, and transforms all observations into a consistent world coordinate frame suitable for Unity-based visualization."),

(P, "The second objective is to develop an upper-body pose estimation module that fuses MediaPipe Pose landmark detections with registered depth data from the RealSense sensor, producing metric 3D joint positions for the torso, arms, and hands simultaneously from a single fixed viewpoint."),

(P, "The third objective is to implement a concurrent object tracking module based on ArUco fiducial markers that estimates the position trajectory of the manipulated object frame by frame, synchronized with the skeletal tracking stream so that hand and object positions are expressed in the same world coordinate frame at each time step. Recovering the full orientation of the object as it is turned by the hands introduces additional challenges, because the marker's visibility and viewing angle are themselves governed by the motion of the arms that manipulate it. These challenges are identified and discussed, and full orientation tracking is left as an extension of the present framework."),

(P, "The fourth objective is to recover occluded or low-confidence landmarks through interpolation and to validate the reconstructed motion against ground truth. The validation centres on three trajectories: the position of the left wrist, the position of the right wrist, and the position of the manipulated object. Each is compared against ground-truth references defined in the experimental setup, so that the MediaPipe-based landmark tracking and the ArUco-based object tracking are evaluated on a common footing. A region-specific recovery scheme, in which each body segment is dispatched to a recovery branch matched to its own kinematic properties, is outlined as a refinement for future work."),

(P, "The fifth and final objective is to integrate the complete pipeline with a Unity-based visualization environment and evaluate the reconstructed output qualitatively by comparing avatar motion against the original RGB-D recordings across a set of representative bimanual manipulation tasks including lifting, rotation, and object transfer between hands."),

(H2, "References"),
]

references = [
'S. Sivakumar, K. Shaw, and D. Pathak, "Robotic telekinesis: Learning a robotic hand imitator by watching humans on YouTube," arXiv:2202.10448, 2022.',
'Y. Ye, P. Hebbar, A. Gupta, and S. Tulsiani, "Diffusion-guided reconstruction of everyday hand-object interaction clips," in Proc. IEEE/CVF Int. Conf. Computer Vision (ICCV), 2023.',
'G. Buckingham, "Hand tracking for immersive virtual reality: Opportunities and challenges," Frontiers in Virtual Reality, vol. 2, p. 728461, 2021.',
'M. Mangalam et al., "Enhancing hand-object interactions in virtual reality for precision manual tasks," Virtual Reality, vol. 28, no. 4, 2024.',
'R. J. Carey, L. T. Baxter, and P. R. Di Fabio, "Tracking control in the nonparetic hand of subjects with stroke," Archives of Physical Medicine and Rehabilitation, vol. 79, no. 4, pp. 435-441, 1998.',
'C. D. Hayden et al., "Measurement of upper limb function in ALS: A structured review of current methods and future directions," Journal of Neurology, vol. 269, no. 8, pp. 4089-4101, 2022.',
'X. Zhan et al., "OakInk2: A dataset of bimanual hands-object manipulation in complex task completion," in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR), 2024.',
'E. Theodoridou et al., "Hand tracking and gesture recognition by multiple contactless sensors: A survey," IEEE Transactions on Human-Machine Systems, vol. 53, no. 1, pp. 35-43, 2023.',
'L. Keselman, J. Iselin Woodfill, A. Grunnet-Jepsen, and A. Bhowmik, "Intel RealSense stereoscopic depth cameras," in Proc. IEEE Conf. Computer Vision and Pattern Recognition Workshops (CVPRW), 2017.',
'H. Meng et al., "3D interacting hand pose estimation by hand de-occlusion and removal," in Proc. European Conf. Computer Vision (ECCV), 2022.',
'R. Wang, W. Mao, and H. Li, "Interacting hand-object pose estimation via dense mutual attention," in Proc. IEEE/CVF Winter Conf. Applications of Computer Vision (WACV), 2023.',
'S. Dill et al., "Accuracy evaluation of 3D pose reconstruction algorithms through stereo camera information fusion for physical exercises with MediaPipe Pose," Sensors, vol. 24, no. 23, art. 7772, 2024.',
'Y. Dong, "Tracking and reconstruction of object grasping hand using a RGB-D sensor," M.A.Sc. thesis, Simon Fraser University, 2024.',
'A. Ahmad, C. Migniot, and A. Dipanda, "Hand pose estimation and tracking in real and virtual interaction: A review," Image and Vision Computing, vol. 89, pp. 35-49, 2019.',
'Y. Dong and S. Payandeh, "Hand kinematic model construction based on tracking landmarks," Applied Sciences, vol. 15, no. 16, p. 8921, 2025, doi: 10.3390/app15168921.',
'Y. Dong and S. Payandeh, "Bayesian estimation of hand kinematics from spatially tracked landmarks," Journal of Intelligent Systems and Control, vol. 4, no. 2, pp. 105-124, 2025, doi: 10.56578/jisc040203.',
'A. Ahmad, C. Migniot, and A. Dipanda, "Tracking hands in interaction with objects: A review," in Proc. Int. Conf. Signal-Image Technology and Internet-Based Systems (SITIS), 2017.',
'R. Y. Wang and J. Popovic, "Real-time hand-tracking with a color glove," ACM Transactions on Graphics, vol. 28, no. 3, pp. 1-8, 2009.',
'C. Diaz and S. Payandeh, "Multimodal sensing interface for haptic interaction," Journal of Sensors, vol. 2017, art. 2072951, pp. 1-24, 2017, doi: 10.1155/2017/2072951.',
'I. Oikonomidis, N. Kyriazis, and A. A. Argyros, "Efficient model-based 3D tracking of hand articulations using Kinect," in Proc. British Machine Vision Conf. (BMVC), 2011.',
'A. Tagliasacchi et al., "Robust articulated-ICP for real-time hand tracking," Computer Graphics Forum, vol. 34, no. 5, pp. 101-114, 2015.',
'C. Qian, X. Sun, Y. Wei, X. Tang, and J. Sun, "Realtime and robust hand tracking from depth," in Proc. IEEE Conf. Computer Vision and Pattern Recognition (CVPR), 2014.',
'L. Ge, H. Liang, J. Yuan, and D. Thalmann, "Robust 3D hand pose estimation from single depth images using multi-view CNNs," IEEE Transactions on Image Processing, vol. 27, no. 9, pp. 4422-4436, 2018.',
'G. Pavlakos, D. Shan, I. Radosavovic, A. Kanazawa, D. Fouhey, and J. Malik, "Reconstructing hands in 3D with transformers," in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR), 2024.',
'H. Dong et al., "Hamba: Single-view 3D hand reconstruction with graph-guided bi-scanning Mamba," in Advances in Neural Information Processing Systems, vol. 37, pp. 2127-2160, 2024.',
'F. Zhang et al., "MediaPipe Hands: On-device real-time hand tracking," arXiv:2006.10214, 2020.',
'M. Kalaitzakis, B. Cain, S. Carroll, A. Ambrosi, C. Whitehead, and N. Vitzilaios, "Fiducial markers for pose estimation: Overview, applications and experimental comparison," Journal of Intelligent and Robotic Systems, vol. 101, art. 71, 2021.',
'J. L. Pulloquinga, D. Corrata, V. Mata, A. Valera, and M. Valles, "Experimental analysis of pose estimation based on ArUco markers," in Innovations in Industrial Engineering III (Lecture Notes in Mechanical Engineering), Cham: Springer, 2024, pp. 138-149.',
'F. Krebs and T. Asfour, "Formalization of temporal and spatial constraints of bimanual manipulation categories," in Proc. IEEE/RSJ Int. Conf. Intelligent Robots and Systems (IROS), 2024.',
'G. Moon, S.-I. Yu, H. Wen, T. Shiratori, and K. M. Lee, "InterHand2.6M: A dataset and baseline for 3D interacting hand pose estimation from a single RGB image," in Proc. European Conf. Computer Vision (ECCV), 2020.',
'W. Wang et al., "RGB2Hands: Real-time tracking of 3D hand interactions from monocular RGB video," ACM Transactions on Graphics, vol. 39, no. 6, 2020.',
'T.-W. Chen and W.-L. Lin, "3D human motion reconstruction in Unity with monocular camera," in Proc. Int. SoC Design Conf. (ISOCC), 2020.',
'V. N. Dubey and S. K. Manna, "Design of a game-based rehabilitation system using Kinect sensor," in Proc. ASME Design of Medical Devices Conf. (DMD), 2019.',
'Y. Chen et al., "RePose: A real-time 3D human pose estimation and biomechanical analysis framework for rehabilitation," arXiv:2601.00625, 2026.',
'M. S. Ahn, H. Chae, D. Noh, H. Nam, and D. Hong, "Analysis and noise modeling of the Intel RealSense D435 for mobile robots," in Proc. Int. Conf. Ubiquitous Robots (UR), 2019.',
'E. Curto and H. Araujo, "Fitting a normal probability distribution to depth estimations of three RealSense RGB-D cameras tested in scenes with transparency," ISPRS Annals of the Photogrammetry, Remote Sensing and Spatial Information Sciences, 2022.',
'S. Hampali, M. Rad, M. Oberweger, and V. Lepetit, "HOnnotate: A method for 3D annotation of hand and object poses," in Proc. IEEE/CVF Conf. Computer Vision and Pattern Recognition (CVPR), 2020.',
]

doc = Document()
style = doc.styles["Normal"]
style.font.name = "Times New Roman"
style.font.size = Pt(12)

for kind, text in content:
    if kind == H1:
        doc.add_heading(text, level=1)
    elif kind == H2:
        doc.add_heading(text, level=2)
    elif kind == H3:
        doc.add_heading(text, level=3)
    else:
        doc.add_paragraph(text)

for i, ref in enumerate(references, 1):
    doc.add_paragraph(f"[{i}] {ref}")

out = "/home/luo/Desktop/New_SandBox/writing/v2/Chapter_1_Introduction.docx"
doc.save(out)
print("saved", out, "| paragraphs:", len(content), "| refs:", len(references))
