"""Bind fresh capture provenance without changing frozen scientific files."""
from pathlib import Path
import hashlib,json,sys
import pandas as pd
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2];ALIAS=sys.argv[1] if len(sys.argv)>1 else 'r7';OUT=HERE/ALIAS
sys.path.insert(0,str(ROOT/'eval'));from common import paths
stem=next(k for k,v in paths.ALIAS.items() if v==ALIAS)
N=len(pd.read_csv(OUT/'integrated_stream.csv'))-1
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
angles=ROOT/f'eval/output/recovery_{ALIAS}/angles_recovery.csv';s=pd.read_csv(angles);s=s[s.frame<N][['frame','time_s','live_mask']+[f'tag_{i}'for i in range(7)]];s.to_csv(OUT/'source_group_states.csv',index=False)
sources=[angles,paths.calib_for(stem),paths.lm_filtered(stem),paths.object_world_filtered(stem),ROOT/f'eval/reports/{ALIAS}_rig_sizing.json',ROOT/'eval/unity_check/send_scene_r5.py',ROOT/'Unity/Assets/Scripts/IntegratedSceneReceiver.cs',ROOT/'Unity/Assets/Scripts/ArucoSceneReceiver.cs',ROOT/'Unity/Assets/Scripts/EvalFrameDump.cs',HERE/'DefenseAxes.cs',HERE/'AxesOverlay.shader']
outputs=[OUT/n for n in [f'Fresh_Unity_{ALIAS.upper()}_Model_Axes.mp4','axes_matrices.csv','integrated_stream.csv','unity_person_log.csv','unity_object_log.csv','rig_dimensions.csv','rig_sizing_used.txt','source_group_states.csv','axes_validation.json','check_unity_log.json','check_rig_sizing.txt','render_projection_check.json']]
original=json.loads((OUT/'check_unity_log.json').read_text())
report={'status':'VERIFIED_APPLICATION_WITH_RECORDED_DIAGNOSTIC_LIMIT','stem':stem,'source_frames':{'first':0,'last':N-1,'count':N,'missing_inside_interval':[],'recording_terminal_frame':N,'terminal_frame_status':'not retained by the frozen capture loop'},'capture':'Actual Unity engine render from isolated copied project; newly rendered, not archived thesis result footage.','geometry':f'Five recording-specific {ALIAS} lengths.','axes':{'origins':'Rendered pelvis, shoulders, elbows. Pelvis is explicitly not L24.','orientations':'Composed model bases before authored bone rest offset; bone bases also logged.','colors':{'x':'#FF4040','y':'#40E070','z':'#408CFF'},'length_m':0.12,'width_m':0.004,'visibility':'Explanatory overlay through mesh; ZTest Always, ZWrite Off, Overlay queue.'},'camera':'Unchanged calibrated SensorPOVCamera; 1440x1080 target; world and projection matrices per frame.','timing':{'source_fps':30,'capture_replay_speed':0.25,'export_fps':30},'state':'source_group_states.csv retains saved pre-display recovery tags0measured1held2constrained; displayed angles retain the original sender display smoother. Receiver spheres alone remain binary live/non-live.','validation':{'axes':'PASS','sizing':'12 PASS,0 FAIL; private-path-only copy of originalchecker','original_unity_checker':{'passed':original['passed'],'failed':original['failed'],'qualification':'Raw report preserved. A historical failure-concentration assertion is distinct from exact frame application and anchor checks.'},'accuracy':'Diagnostics validate replay consistency, not anatomical accuracy; no new experiment claim.'},'sources':{str(p.relative_to(ROOT)):sha(p)for p in sources},'outputs':{p.name:sha(p)for p in outputs}}
(OUT/'capture_manifest.json').write_text(json.dumps(report,indent=2)+'\n')
print('Bound',len(sources),'sources and',len(outputs),'outputs')
