#!/usr/bin/env python3
"""Write writing/v8/CH9_SPLIT_TEXT_CHANGES.md: the exact old -> new text of
supervisor round 7 (2026-09-10; abstract rewrite, Chapter 9 split into
Chapters 9 and 10) for hand-syncing an online copy
(skill_set/manual-edit-change-lists.md). The old texts come from the
built parts at commit de74302 (git show); the new texts from the current
builds. The abstract and the two chapters are rewritten end to end, so
they appear in full; the other chapters get FIND / REPLACE WITH pairs.

Run: python3 writing/v8/scripts/make_ch9_split_text_changes.py
"""
import difflib, re, subprocess, tempfile
from pathlib import Path
from docx import Document
from docx.oxml.ns import qn

REPO = Path(__file__).resolve().parents[3]
C = REPO / "writing" / "v8" / "condensed"
OUT = REPO / "writing" / "v8" / "CH9_SPLIT_TEXT_CHANGES.md"
OLD = "de74302"


def blocks(path):
    """(style, text) per body element, tables dumped row by row."""
    doc = Document(path); out = []
    for ch in doc.element.body.iterchildren():
        tag = ch.tag.split('}')[1]
        if tag == 'p':
            txt = ''.join(t.text or '' for t in ch.iter(qn('w:t'))).strip()
            st = ch.find('.//' + qn('w:pStyle'))
            style = st.get(qn('w:val')) if st is not None else ''
            if ch.find('.//' + qn('w:drawing')) is not None:
                out.append(("img", "[FIGURE]")); continue
            if txt: out.append((style, txt))
        elif tag == 'tbl':
            for row in ch.iter(qn('w:tr')):
                cells = [''.join(t.text or '' for t in c.iter(qn('w:t'))).strip() for c in row.iter(qn('w:tc'))]
                out.append(("table", "TABLE | " + " | ".join(cells)))
    return out


def old_blocks(name):
    data = subprocess.run(["git", "-C", str(REPO), "show", f"{OLD}:writing/v8/condensed/{name}"], capture_output=True).stdout
    with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as f:
        f.write(data); tmp = f.name
    return blocks(tmp)


def pairs(old, new):
    ot = [b[1] for b in old]; nt = [b[1] for b in new]
    sm = difflib.SequenceMatcher(a=ot, b=nt, autojunk=False)
    out = []
    for op, i1, i2, j1, j2 in sm.get_opcodes():
        if op == "equal": continue
        if op == "replace" and i2 - i1 == j2 - j1:
            for k in range(i2 - i1): out.append(("REPLACE", ot[i1 + k], nt[j1 + k]))
        else:
            for k in range(i1, i2): out.append(("DELETE", ot[k], None))
            for k in range(j1, j2): out.append(("INSERT", None, nt[k]))
    return out


def sentence_pairs(o, n):
    so = re.split(r"(?<=[.!?])\s+", o); sn = re.split(r"(?<=[.!?])\s+", n)
    sm = difflib.SequenceMatcher(a=so, b=sn, autojunk=False)
    out = []
    for op, i1, i2, j1, j2 in sm.get_opcodes():
        if op == "equal": continue
        out.append((" ".join(so[i1:i2]), " ".join(sn[j1:j2])))
    return out or [(o, n)]


def abstract_from(src):
    a = src.index("ABSTRACT = ["); b = src.index("]\n", a) + 2
    ns = {}; exec(src[a:b], ns); return ns["ABSTRACT"]


lines = [
"# Round 7 (abstract, Chapter 9 split): exact text changes (commit de74302 -> this version, 2026-09-10)",
"",
"Old -> new pairs for hand-syncing an online copy (skill_set/manual-edit-change-lists.md), built by diffing the built parts before and after the round at paragraph level and, inside a changed paragraph, at sentence level. The abstract, Chapter 9 and Chapter 10 are rewritten end to end, so they appear in full: the old abstract as DELETE and the new one as INSERT items, the old Chapter 9 as one DELETE and the two new chapters as INSERT items in order. [FIGURE] marks a picture; a table row is dumped as its cells separated by | . The contents and the lists of figures and tables are regenerated by Word and are not listed.",
"",
]
old_fm = subprocess.run(["git", "-C", str(REPO), "show", f"{OLD}:writing/v8/condensed/scripts/build_frontmatter.py"], capture_output=True, text=True).stdout
new_fm = (C / "scripts" / "build_frontmatter.py").read_text()
lines += ["## Abstract (front matter)", "", "The whole abstract is replaced. Old text (three paragraphs):", ""]
for i, p in enumerate(abstract_from(old_fm), 1): lines += [f"{i}. DELETE: {p}", ""]
lines += ["New text (four paragraphs, in the supervisor's order: the problem and why, the challenges, how they were addressed, what was accomplished):", ""]
for i, p in enumerate(abstract_from(new_fm), 1): lines += [f"{i}. INSERT: {p}", ""]

for title, name in [("Chapter 1", "Chapter_1_Introduction.docx"), ("Chapter 3", "Chapter_3_Kinematic_Modeling.docx"),
                    ("Chapter 7", "Chapter_7_Evaluation.docx"), ("Chapter 8", "Chapter_8_Real_Time_Feasibility.docx"),
                    ("Appendices", "Appendices.docx")]:
    ps = pairs(old_blocks(name), blocks(C / name))
    if not ps: continue
    lines += [f"## {title}", ""]
    n = 0
    for op, o, nw in ps:
        if op == "REPLACE":
            sp = sentence_pairs(o, nw)
            for k, (a, b) in enumerate(sp):
                n += 1; tag = f"{n}" if len(sp) == 1 else f"{n}{'abcdefgh'[k]}"
                lines += [f"{tag}. FIND: {a}", f"    REPLACE WITH: {b}", ""]
        elif op == "DELETE":
            n += 1; lines += [f"{n}. DELETE: {o}", ""]
        else:
            n += 1; lines += [f"{n}. INSERT: {nw}", ""]

lines += ["## Chapter 9 (old): delete the whole chapter", "", "1. DELETE the chapter \"Chapter 9: Discussion, Future Work, and Conclusion\" in full (Sections 9.1 to 9.3, Figures 9.1 and 9.2, Table 9.1). Its text is in the build of commit de74302 (writing/v8/condensed/Chapter_9_Discussion_Conclusion.docx).", ""]
for title, name in [("Chapter 9 (new): insert in full", "Chapter_9_Discussion.docx"),
                    ("Chapter 10 (new): insert in full", "Chapter_10_Conclusions_Future_Work.docx")]:
    lines += [f"## {title}", ""]
    for i, (style, txt) in enumerate(blocks(C / name), 1):
        lines += [f"{i}. INSERT{' (heading)' if style.startswith('Heading') else ''}: {txt}", ""]

OUT.write_text("\n".join(lines) + "\n")
print("saved", OUT, len(lines), "lines")
